[template.environment]
  GQL_HOST = "https://wp.grabxyz.com"
  NUXT_IMAGE_DOMAINS = "Comma separated list of domains. example.com,example2.com"

[build]
  command = "nuxt generate"
  publish = "dist"
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[images]
  remote_images = ["https://secure.woonuxt.com/.*"]
